### ISSUE TITLE
[Bug]: ImportError: cannot import name 'types' from 'cryptography.hazmat.primitives.asymmetric'

### ISSUE THREAD

**Issue by VVD** [certbot/certbot#10303]
### OS

FreeBSD 14.2

### Installation method

ports

### Certbot Version

4.0.0

### What happened?

```shell
# certbot --help
Traceback (most recent call last):
  File "/usr/local/bin/certbot", line 5, in <module>
    from certbot.main import main
  File "/usr/local/lib/python3.11/site-packages/certbot/main.py", line 6, in <module>
    from certbot._internal import main as internal_main
  File "/usr/local/lib/python3.11/site-packages/certbot/_internal/main.py", line 24, in <module>
    from acme import client as acme_client
  File "/usr/local/lib/python3.11/site-packages/acme/client.py", line 25, in <module>
    from acme import challenges
  File "/usr/local/lib/python3.11/site-packages/acme/challenges.py", line 24, in <module>
    from acme import crypto_util
  File "/usr/local/lib/python3.11/site-packages/acme/crypto_util.py", line 22, in <module>
    from cryptography.hazmat.primitives.asymmetric import dsa, rsa, ec, ed25519, ed448, types
ImportError: cannot import name 'types' from 'cryptography.hazmat.primitives.asymmetric' (/usr/local/lib/python3.11/site-packages/cryptography/hazmat/primitives/asymmetric/__init__.py)
```

### Expected behavior

Show help message. :-)

This line from this commit produces an error:
https://github.com/certbot/certbot/commit/e050fe91a3c8f27ed883fc31aaa3bc7c89aafd6e#diff-035393341b36c4adff76feb0627156920de618857c156c42335ef9b0437de6feR22-R23

### Relevant log output

```shell

```

**Comment by VVD** [comment]
After dirty-hacks:
```diff
--- acme/crypto_util.py.orig    2025-04-07 22:03:33 UTC
+++ acme/crypto_util.py
@@ -19,7 +19,8 @@ from cryptography.hazmat.primitives import hashes, ser

 from cryptography import x509
 from cryptography.hazmat.primitives import hashes, serialization
-from cryptography.hazmat.primitives.asymmetric import dsa, rsa, ec, ed25519, ed448, types
+from cryptography.hazmat.primitives.asymmetric import dsa, rsa, ec, ed25519, ed448
+#, types
 from cryptography.hazmat.primitives.serialization import Encoding
 from OpenSSL import crypto
 from OpenSSL import SSL
@@ -58,7 +59,7 @@ _KeyAndCert = Union[

 _KeyAndCert = Union[
     Tuple[crypto.PKey, crypto.X509],
-    Tuple[types.CertificateIssuerPrivateKeyTypes, x509.Certificate],
+#    Tuple[types.CertificateIssuerPrivateKeyTypes, x509.Certificate],
 ]


@@ -390,8 +391,15 @@ def _now() -> datetime:
 def _now() -> datetime:
     return datetime.now(tz=timezone.utc)

+CertificateIssuerPrivateKeyTypes = Union[
+    dsa.DSAPrivateKey,
+    rsa.RSAPrivateKey,
+    ec.EllipticCurvePrivateKey,
+    ed25519.Ed25519PrivateKey,
+    ed448.Ed448PrivateKey,
+]

-def make_self_signed_cert(private_key: types.CertificateIssuerPrivateKeyTypes,
+def make_self_signed_cert(private_key: CertificateIssuerPrivateKeyTypes,#types.CertificateIssuerPrivateKeyTypes,
                           domains: Optional[List[str]] = None,
                           not_before: Optional[datetime] = None,
                           validity: Optional[timedelta] = None, force_san: bool = True,
@@ -408,8 +416,8 @@ def make_self_signed_cert(private_key: types.Certifica
     :param validity: Duration for which the cert will be valid. Defaults to 1
     week
     :type validity: `datetime.timedelta`
-    :param buffer private_key_pem: One of
-    `cryptography.hazmat.primitives.asymmetric.types.CertificateIssuerPrivateKeyTypes`
+    :param buffer private_key_pem: One of `CertificateIssuerPrivateKeyTypes`
+#    `cryptography.hazmat.primitives.asymmetric.types.CertificateIssuerPrivateKeyTypes`
     :param bool force_san:
     :param extensions: List of additional extensions to include in the cert.
     :type extensions: `list` of `x509.Extension[x509.ExtensionType]`
```
```diff
--- certbot/_internal/plugins/standalone.py.orig        2025-04-07 22:03:33 UTC
+++ certbot/_internal/plugins/standalone.py
@@ -24,7 +24,7 @@ from cryptography import x509
 from certbot.plugins import common

 from cryptography import x509
-from cryptography.hazmat.primitives.asymmetric import types
+#from cryptography.hazmat.primitives.asymmetric import types
 from OpenSSL import crypto

 logger = logging.getLogger(__name__)
@@ -37,7 +37,7 @@ _KeyAndCert = Union[

 _KeyAndCert = Union[
     Tuple[crypto.PKey, crypto.X509],
-    Tuple[types.CertificateIssuerPrivateKeyTypes, x509.Certificate],
+#    Tuple[types.CertificateIssuerPrivateKeyTypes, x509.Certificate],
 ]
 
 
```
Errors during renew certs:
```
2025-05-31 05:16:03,795:WARNING:certbot._internal.storage:An error occurred determining the OCSP status of /usr/local/etc/letsencrypt/archive/${DOMAIN}/cert4.pem.
2025-05-31 05:16:03,796:DEBUG:certbot._internal.storage:'_Certificate' object has no attribute 'not_valid_after_utc'
2025-05-31 05:16:03,797:ERROR:certbot._internal.renewal:Failed to renew certificate ${DOMAIN} with error: '_Certificate' object has no attribute 'not_valid_before_utc'
2025-05-31 05:16:03,799:DEBUG:certbot._internal.renewal:Traceback was:
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/certbot/_internal/renewal.py", line 525, in handle_renewal_request
    if should_renew(lineage_config, renewal_candidate):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/certbot/_internal/renewal.py", line 316, in should_renew
    if lineage.should_autorenew():
       ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/certbot/_internal/storage.py", line 1005, in should_autorenew
    notBefore = crypto_util.notBefore(cert)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/certbot/crypto_util.py", line 476, in notBefore
    return cert.not_valid_before_utc
           ^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: '_Certificate' object has no attribute 'not_valid_before_utc'
```

**Comment by zoracon** [comment]
It appears FreeBSD is ignoring the version we declare here: https://github.com/certbot/certbot/blob/v4.0.0/certbot/setup.py#L34

This issue would need to be brought to FreeBSD to not ignore this and grab a version it decides.

**Comment by VVD** [comment]
I'm using last rust-cancer-free version of the cryptography 3.4.8 on this host - weak router with "SSL termination"+reverse http proxy for services in local network. It work fine with certbot 3.2.0.
There is also 44.0.3 in ports, but build rust on this host isn't good idea.
I'll try to look at alternatives to certbot - maybe there's already something suitable…

**Comment by mikhailter** [comment]
> It appears FreeBSD is ignoring the version we declare here: https://github.com/certbot/certbot/blob/v4.0.0/certbot/setup.py#L34
> 
> This issue would need to be brought to FreeBSD to not ignore this and grab a version it decides.

Hello,

this means that it should be used with py-cryptography only, that is needs to be installed with rust? Not every host can compile rust module so why we are using py-cryptography-legacy package.

**Comment by yermulnik** [comment]
+1 to the issue from yet another user who isn't able to build recent Rust at a tiny FreeBSD host =(

**Comment by yermulnik** [comment]
@zoracon Could you please share whether there is no plan on supporting rust-free installation of `certbot`? Thanks.
