### ISSUE TITLE
Certbot not working on Ubuntu 16.04

### ISSUE THREAD

**Issue by StianOvrevage** [certbot/certbot#5326]
## My operating system is (include version):
VERSION="16.04.3 LTS (Xenial Xerus)"

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
pip3 install letsencrypt

## I ran this command and it produced this output:

# certbot
Traceback (most recent call last):
  File "/usr/local/bin/certbot", line 7, in <module>
    from certbot.main import main
  File "/usr/local/lib/python3.5/dist-packages/certbot/main.py", line 11, in <module>
    from acme import jose
  File "/usr/local/lib/python3.5/dist-packages/acme/jose/__init__.py", line 37, in <module>
    from acme.jose.interfaces import JSONDeSerializable
  File "/usr/local/lib/python3.5/dist-packages/acme/jose/interfaces.py", line 9, in <module>
    from acme.jose import util
  File "/usr/local/lib/python3.5/dist-packages/acme/jose/util.py", line 5, in <module>
    import OpenSSL
  File "/usr/local/lib/python3.5/dist-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import crypto, SSL
  File "/usr/local/lib/python3.5/dist-packages/OpenSSL/SSL.py", line 204, in <module>
    if _lib.Cryptography_HAS_SSL_ST:
AttributeError: module 'lib' has no attribute 'Cryptography_HAS_SSL_ST'

## Certbot's behavior differed from what I expected because:
I expected it not to crash.

**Comment by bmw** [comment]
We strongly discourage and do not support installing Certbot through `pip` unless you're using a virtual environment. See [this](https://certbot.eff.org/docs/install.html#installing-from-source).

Instead, I recommend you follow the instructions found [here](https://certbot.eff.org/#ubuntuxenial-other) and open another issue if you encounter a problem. I hope this helps!

**Comment by StianOvrevage** [comment]
Thanks for your reply. Since I'm using Windows pip is the only package-managed version of certbot I could find. I also discovered that you don't support Windows at all. Hence my venture into Docker-territory!
