### ISSUE TITLE
[PATCH] >=0.22.0: Bug in acme.Client.__init__ breaks acme.Client.register

### ISSUE THREAD

**Issue by hartwork** [certbot/certbot#5738]
Hi!

There is a bug in `acme.Client.__init__`. When called with `net=None`, `self.net` is first initialited with a new instance of `ClientNetwork` but then `net` (rather than `self.net`) is pass to `ClientBase.__init__` which sets `self.net` back to None. The breaking code was introduced in 9baf75d6c887a9b69bd92c7bffe585f091c9b08e and is this:
```
class ClientBase(object):  # pylint: disable=too-many-instance-attributes
    [..]
    def __init__(self, directory, net, acme_version):
        [..]
        self.net = net
[..]
class Client(ClientBase):
    [..]
    def __init__(self, directory, key, alg=jose.RS256, verify_ssl=True,
                 net=None):
        [..]
        self.net = ClientNetwork(key, alg=alg, verify_ssl=verify_ssl) if net is None else net
        [..]
        super(Client, self).__init__(directory=directory,
            net=net, acme_version=1)
```
As a result, calling `.register(...)` on the client will raise `AttributeError: 'NoneType' object has no attribute 'post'` which breaks wile, see https://github.com/costela/wile/issues/34.

One way to fix the issue is to change `net=net` to `self.net=net` in the line using `super`. I could provide a pull request to do that if that's the way you want to patch it.

What do you think?

**Comment by bmw** [comment]
You're right! Sorry for the trouble @hartwork, we'll include a patch fixing this in our 0.22.1 release which we're planning on releasing early next week.

I don't have too strong of a preference on how this is fixed and we'd gladly accept a pull request. The way I'd do it personally is always set `self.net` for the first time in `ClientBase` so the relevant code in `Client.__init__` looks something like:
```
if net is None:
    net = ClientNetwork(...)
[...]
super(Client, self).__init__(directory=directory,
    net=net, acme_version=1)
```
If you like your approach better, it's pretty much equivalent so feel free to go with that.

Bonus points if you add a test to `acme/acme/client_test.py` to prevent regressions here. Probably the best way to do that is through using `mock.patch` to mock out `acme.client.ClientNetwork` during the new test.

**Comment by bmw** [comment]
I went ahead and implemented the fix and test for this. Sorry I didn't give you much time. We're just finishing out the work for the release and I wanted to get this out of the way.

Thanks for the offer and reporting the bug though!
