### ISSUE TITLE
AttributeError: 'Namespace' object has no attribute 'changes_since_path'

### ISSUE THREAD

**Issue by frankw2** [certbot/certbot#3012]
This error comes up when I try to use certbot-auto with apache, so it is unable to set up enhancement redirect.

**Comment by bmw** [comment]
This looks like a bug that was introduced in #2794. It'll be fixed in the next release which should come out in the next week or so.

**Comment by frankw2** [comment]
It looks like I'm still getting this bug when I use certbot-auto with apache even with the most recent pull.

**Comment by bmw** [comment]
While this PR has landed in `master`, it hasn't been included in a release yet. It will be in the 0.7.0 release later this week.
