### ISSUE TITLE
compat/os.py missing

### ISSUE THREAD

**Issue by fmunteanu** [certbot/certbot#6990]
After upgrading to 0.33.1, I noticed the `compat/os.py` related files are not present anymore, these are the only ones I have:
```
   /usr/lib/python2.7/site-packages/certbot/compat/__init__.py
   /usr/lib/python2.7/site-packages/certbot/compat/__init__.pyc
   /usr/lib/python2.7/site-packages/certbot/compat/__init__.pyo
   /usr/lib/python2.7/site-packages/certbot/compat/misc.py
   /usr/lib/python2.7/site-packages/certbot/compat/misc.pyc
   /usr/lib/python2.7/site-packages/certbot/compat/misc.pyo

>>> from certbot.compat import misc
>>> from certbot.compat import os
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name os
>>> from certbot.plugins import common
```

This will result in expected errors like `AttributeError: 'module' object has no attribute 'os_geteuid'`. Running the usual command will install everything except the `compat/os.py(c|o)` files:
```
/usr/bin/python2 setup.py  install -O1 --skip-build --root /home/floren/rpm/BUILDROOT
```

CentOS 7.6 details:
```
$ uname -a
Linux chronos 3.10.0-957.10.1.el7.x86_64 #1 SMP Mon Mar 18 15:06:45 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
$ rpm -q python
python-2.7.5-77.el7_6.x86_64
```

Can you please let me know what would be the fix or if there is a patch I can apply until next release fix? I'm building an RPM package.

**Comment by fmunteanu** [comment]
certbot-nginx was an older version, issue resolved.

**Comment by alanmontgomery** [comment]
> certbot-nginx was an older version, issue resolved.

Hey dude. Was it as simple as updating certbox-nginx?
